CREATE TABLE book
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title     VARCHAR UNIQUE NOT NULL,
    author    VARCHAR        NOT NULL,
    published SMALLINT       NOT NULL,
    CHECK (published > 0 AND published <= DATE_PART('year', CURRENT_DATE))
);

INSERT INTO book (title, author, published)
VALUES ('The Prince', 'Niccolo Machiavelli', 1532),
       ('Ulysses', 'James Joyce', 1904),
       ('The Sound and the Fury', 'William Faulkner', 1929),
       ('Invisible Man', 'Ralph Ellison', 1952),
       ('To the Lighthouse', 'Virginia Woolf', 1927),
       ('The Divine Comedy', 'Dante Alighieri', 1472),
       ('The Canterbury Tales', 'Geoffrey Chaucer', 1387),
       ('Things Fall Apart', 'Chinua Achebe', 1958),
       ('Gone with the Wind', 'Margaret Mitchell', 1936),
       ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 1967),
       ('Beloved', 'Toni Morrison', 1987),
       ('The Grapes of Wrath', 'John Steinbeck', 1939),
       ('Mrs. Dalloway', 'Virginia Woolf', 1925),
       ('Native Son', 'Richard Wright', 1940),
       ('Democracy in America', 'Alexis de Tocqueville', 1835),
       ('On the Origin of Species', 'Charles Darwin', 1859),
       ('On the Social Contract', 'Jean-Jacques Rousseau', 1762),
       ('Leviathan', 'Thomas Hobbes', 1651),
       ('The Lord of the Rings', 'J. R. R. Tolkien', 1954);