CREATE TABLE reader
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR        NOT NULL,
    birthday DATE           NOT NULL,
    email    VARCHAR UNIQUE NOT NULL
);

INSERT INTO reader (name, birthday, email)
VALUES ('Chris Williams', '2000-03-05', 'c.williams@email.com'),
       ('Martha Matthews', '2004-03-14', 'm.matthews@email.com'),
       ('Randall Dean', '1999-12-16', 'r.dean@email.com'),
       ('Geraldine Hernandez', '1967-10-11', 'g.hernandez@email.com'),
       ('Alexander Johnson', '2012-01-31', 'a.johnson@email.com'),
       ('Susan Lawrence', '2000-01-01', 's.lawrence@email.com'),
       ('Deborah Jackson', '2005-12-10', 'd.jackson@email.com'),
       ('Jason Taylor', '2000-05-12', 'j.taylor@email.com'),
       ('Marjorie Johnson', '1988-07-30', 'm.johnson@email.com'),
       ('Anthony Hall', '1999-02-20', 'a.hall@email.com');
